blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

# To create a new post
class PostForm(FlaskForm):
    title = StringField('Post Title', validators=[DataRequired()])
    content = TextAreaField("Content Here", validators=[DataRequired()])
    submit = SubmitField('Post')

blog/main/routes.py
from flask import Blueprint, render_template, request
from blog.models import Post

main = Blueprint('main', __name__)

# The 'HOME' route, to the 'HOME' route
@main.route("/")
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

# The 'ABOUT' route, to the 'ABOUT' route
@main.route('/about')
def about():
    return render_template('about.html', title='About')

blog/posts/routes.py
from flask import Blueprint, request, redirect, render_template, abort, flash, url_for
from blog.posts.forms import PostForm
from blog.models import Post
from blog import db
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

#this is a route to create a new post
@posts.route('/posts/new', methods=['POST', 'GET'])
@login_required

def new_post():
    form = PostForm()
    if form.validate_on_submit():
    #Commits and saves posts to the database
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()

        flash('Your post has been created successfully!', 'success')
        return redirect(url_for('main.home'))
        
    return render_template('create_post.html', title='New Post', form=form)

# This is a route to view our post
@posts.route('/posts/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

# This is a route to update our post
@posts.route('/posts/<int:post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been successfully been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    if request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    
    return render_template('update_post.html', title=f'Update Post-{post.author.username}', form=form)

# This is a route to delete your post
@posts.route('/posts/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'danger')
    return redirect(url_for('main.home'))

blog/users/routes.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import current_user, logout_user, login_user, login_required
from blog import db, bcrypt
from blog.models import User, Post
from blog.users.forms import LoginForm, RegistrationForm, UpdateAccountForm, RequestPasswordForm, ResetPasswordForm
from blog.users.utils import save_picture, send_reset_email
from sqlalchemy.exc import IntegrityError

users = Blueprint('users', __name__)

# The 'LOGIN' route, to the 'LOGIN' route
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Welcome {form.username.data}!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home')) # Itinenary conditionals
        else:
            flash('Login Failed! Check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)
    
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

# The 'REGISTER' route, to the 'REGISTER' route
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Hello {form.username.data}, your account has been created. Please log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
# The 'LOGOUT' route, to the 'LOGOUT' and other routes   
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        try:
            db.session.commit() # Commits the saved username and email to the db
            flash(f'Hi {current_user.username}, your account has been updated!', 'success') # Flashes the success message
            return redirect(url_for('users.account'))
        # It solves the user exists error
        except IntegrityError:
            db.session.rollback() 
            flash('This email or username is taken.', 'danger')
    
    elif request.method == 'GET':
        # Populates the form with the current user's details
        form.username.data = current_user.username
        form.email.data = current_user.email
        
    if current_user.image_file:
        image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    else:
       image_file = url_for('static', filename='profile_pics/default.jpg')  # Provide a default image file
    return render_template('account.html', title='Account', image_file=image_file, form=form)

# A route to show the user's posts and profile
@users.route('/user/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)     
    return render_template('user_posts.html', posts=posts, user=user)

# This is a route to request for a pass reset
@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email with instructions on how to reset your password has been sent to your email', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset password', form=form)

# This is a route to reset your password
@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_user_token(token)
    if user is None:
        flash('This is an invalid or expired token, try again.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Hello {form.username.data}, your password has been updated! Please log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset your password', form=form)

blog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>About us</h1>
{%endblock content%}

blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
<!-- User profile photo and username section -->
    <div class="content-section">
        <div class="media custom-border">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <!-- FORM HERE -->
            <form method="post", action="", enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class='form-group'>
                    <legend class="border-bottom mb-4">Account Information</legend>
                    <!-- Update username -->
                    <div class="form-group">
                        {{ form.username.label(class='form-control-label') }}
                        {% if form.username.errors %}
                            {{ form.username(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                    <!-- Update email -->
                    <div class="form-group">
                        {{ form.email.label(class='form-control-label') }}
                        {% if form.email.errors %}
                            {{ form.email(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                    <!-- Update your profile picture -->
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class='form-control-file') }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">
                                    {{ error }}
                                </span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class='btn btn-outline-info') }}
                </div>
            </form>
    </div>
{%endblock content%}

blog/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <!-- FORM HERE -->
            <form method="post", action="", enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class='form-group'>
                    <legend class="border-bottom mb-4">Create a new post</legend>
                    <!-- Title -->
                    <div class="form-group">
                        {{ form.title.label(class='form-control-label') }}
                        {% if form.title.errors %}
                            {{ form.title(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                    <!-- Post Content -->
                    <div class="form-group">
                        {{ form.content.label(class='form-control-label') }}
                        {% if form.content.errors %}
                            {{ form.content(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class='btn btn-outline-info') }}
                </div>
            </form>
    </div>
{% endblock content %}

blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %} <!-- posts.items because its now a pagination object -->
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/') + post.author.image_file }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">>{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id ) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...  <!-- Places the 'None' pages inside an ellipse -->
        {% endif %}
    {% endfor %}
{% endblock content %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Blog Home Page - {{ title }}</title>
    {% else %}
        <title>Blog Home Page</title>
    {% endif %}
</head>
<body>
    <!-- Navbar -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">an1me.co</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}"><i class="fa-solid fa-house"></i> Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}"><i class="fa-solid fa-question"></i> About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}"><i class="fa-brands fa-usps"></i> New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}"><i class="fa-solid fa-user"></i> Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"><i class="fa-solid fa-right-from-bracket"></i> Log Out</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}"><i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}"><i class="fa-solid fa-user-plus"></i> Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    
    <!-- Flashing messages 'success', 'danger' -->
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
            {% block content %}
            {% endblock %}
          </div>
          <!-- Side Bar, add content? -->
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
    </main>
 
    <!-- Optional Javascript, bootstrap and the popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/12ffeedcea.js" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="post", action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class="border-bottom mb-4">Log In</legend>
                <!-- Username login -->
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <!-- Password login -->
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
                <small class="text-muted ml-4">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            
        </form>
    </div>
{% endblock content %}

blog/templates/modal.html
{% extends 'layout.html' %}
{% block content %}
<!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">
        Launch demo modal
    </button>
  
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/') + post.author.image_file }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">>{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          {% if post.author == current_user %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Edit</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
          {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          This would permanently delete your post!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}





blog/templates/reset_request.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
        <form method="post", action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class="border-bottom mb-4">Reset Your Password</legend>
                <!-- Email -->
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/update_post.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <!-- FORM HERE -->
            <form method="post", action="", enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class='form-group'>
                    <legend class="border-bottom mb-4">Update Post</legend>
                    <!-- Title -->
                    <div class="form-group">
                        {{ form.title.label(class='form-control-label') }}
                        {% if form.title.errors %}
                            {{ form.title(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                    <!-- Post Content -->
                    <div class="form-group">
                        {{ form.content.label(class='form-control-label') }}
                        {% if form.content.errors %}
                            {{ form.content(class='form-control form-control-lg is-invalid') }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>
                                        {{ error }}
                                    </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class='form-control form-control-lg') }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class='btn btn-outline-info') }}
                </div>
            </form>
    </div>
{% endblock content %}

blog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %} <!-- posts.items because its now a pagination object -->
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/') + post.author.image_file }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id ) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home',username=user.username, page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...  <!-- Places the 'None' pages inside an ellipse -->
        {% endif %}
    {% endfor %}
{% endblock content %}